version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=sibin@1234
      - DATABASE_HOST=db
      - DATABASE_NAME=SJU
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=sibin@1234
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD=sibin@1234
      MYSQL_DATABASE=SJU
      MYSQL_USER=root
      MYSQL_PASSWORD=sibin@1234
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    command: redis-server --requirepass sibin@1234

volumes:
  db_data: