version: '3.8'

services:
  ai_backend:
    build: ./ai_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: academic_system
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: